# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ab964b813e756bcbd6f1be9fb17a53f302b9c4bc26700dda21efb7de3809c4d5551fe7f59674a2284af0cbd9a092046b904e055289b11c7344e75dd15e47ca7

test:
  secret_key_base: 647b7be1bf5f80d9bf2568abf52193b79e375b00cd8a06c1e9a7757a066fa7d8cd8e443a90cfcb6ef979d0fad649ce4d6c7875ffdfd1f2992f6d0adcd005ad7d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
